version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    environment:
      MINIO_ACCESS_KEY: 90197DB1-E4FD-4B6D-8763-48C33A15026B
      MINIO_SECRET_KEY: 7F6A58C2-F862-4EE8-95DE-375B4A46BD48
    command: server /data

  image-resizer:
    image: appleboy/nginx-image-resizer
    container_name: image-resizer
    ports:
      - 8002:80
    volumes:
      - cache-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    environment:
      IMAGE_HOST: http://minio:9000
      NGINX_HOST: 192.168.43.128

volumes:
  minio-data:
  cache-data:
